version: '3.9'

services:
  auth-db:
    image: postgres:16-alpine
    container_name: auth_db
    environment:
      POSTGRES_DB: ${AUTH_DB_NAME}
      POSTGRES_USER: ${AUTH_DB_USERNAME}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  user-db:
    image: postgres:16-alpine
    container_name: user_db
    environment:
      POSTGRES_DB: ${USER_DB_NAME}
      POSTGRES_USER: ${USER_DB_USERNAME}
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD}
    volumes:
      - user_postgres_data:/var/lib/postgresql/data
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  order-db:
    image: postgres:16-alpine
    container_name: order_db
    environment:
      POSTGRES_DB: ${ORDER_DB_NAME}
      POSTGRES_USER: ${ORDER_DB_USERNAME}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    networks:
      - microservice-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

  payment-mongodb:
    image: mongo:latest
    container_name: ${PAYMENT_MONGODB_HOST}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${PAYMENT_DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${PAYMENT_DB_PASS}
      - MONGO_INITDB_DATABASE=${PAYMENT_DB_NAME}
    networks:
      - microservice-network

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://:29092,CONTROLLER://:29093'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      CLUSTER_ID: '${KAFKA_CLUSTER_ID}'
    networks:
      - microservice-network

  redis:
    image: redis:7.2-alpine
    container_name: common_redis
    volumes:
      - redis_data:/data
    networks:
      - microservice-network

  auth-service:
    build:
      context: "../Authentication Service"
      dockerfile: Dockerfile
    container_name: auth_service
    env_file:
      - .env.docker
    ports:
      - "8081:8081"
    depends_on:
      auth-db:
        condition: service_healthy
    networks:
      - microservice-network

  user-service:
    build:
      context: ../UserService
      dockerfile: Dockerfile
    container_name: user_service
    env_file:
      - .env.docker
    ports:
      - "8080:8080"
    depends_on:
      user-db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - microservice-network

  order-service:
    build:
      context: ../OrderService
      dockerfile: Dockerfile
    container_name: order_service
    env_file:
      - .env.docker
    ports:
      - "8084:8084"
    depends_on:
      order-db:
        condition: service_healthy
    networks:
      - microservice-network

  payment-service:
    build:
      context: ../PaymentService
      dockerfile: Dockerfile
    container_name: payment_service
    env_file:
      - .env.docker
    ports:
      - "${PAYMENT_SERVICE_PORT}:${PAYMENT_SERVICE_PORT}"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://${PAYMENT_DB_USER}:${PAYMENT_DB_PASS}@${PAYMENT_MONGODB_HOST}:${PAYMENT_MONGODB_PORT}/${PAYMENT_DB_NAME}?authSource=admin
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
    depends_on:
      - payment-mongodb
      - kafka
    networks:
      - microservice-network

  api-gateway:
    build:
      context: ../ApiGateway
      dockerfile: Dockerfile
    container_name: api_gateway
    env_file:
      - .env.docker
    ports:
      - "8085:8085"
    depends_on:
      auth-service: { condition: service_started }
      user-service: { condition: service_started }
      order-service: { condition: service_started }
      payment-service: { condition: service_started }
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  redis_data:
  auth_postgres_data:
  user_postgres_data:
  order_postgres_data: