global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'spring-boot-services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'user-service:8080'
          - 'auth-service:8081'
          - 'order-service:8084'
          - 'api-gateway:8085'
          - 'payment-service:8086'